name: django-pgstats
channels:
  - conda-forge
dependencies:
  - python==3.14.0
  - poetry==2.2.1
  - pip==25.3
  - postgresql==18.0
variables:
  DATABASE_URL: "postgres://postgres@localhost:5432/pgstats_local"
  EXEC_WRAPPER: ""
